### ISSUE TITLE
Crash when application is not compiled with /DEBUG

### ISSUE THREAD

**Issue by dashdash12** [botman99/AeonProfiler#1]
When the application is not compiled with /DEBUG flag, e.g. in release version the profiler crashes when I click "Capture" in the dialog. Also the thread list is empty.

**Comment by botman99** [comment]
Hmmm, this may have something to do with the logging in the DebugLog class (which I changed soon before my initial commit to github).  I'll see if I can reproduce the crash and try to fix it up as soon as possible.

**Comment by dashdash12** [comment]
I tested further and found out that it only happens when i generate my project files with CMake.

I use the simplest CMake file possible:

```
project(test1)
add_executable(test1.exe Main.cpp)
```

**Comment by botman99** [comment]
Yeah, the project files included in the github depot define "_DEBUG" when building a Debug configuration (and define NDEBUG when not building a Debug configuration).

**Comment by botman99** [comment]
This should be resolved in the following commit:

https://github.com/botman99/AeonProfiler/commit/3fbc673291139569e00b55e49e70025728ce0a5b
