### ISSUE TITLE
Hey Question about AeonProfiler

### ISSUE THREAD

**Issue by fatrolls** [botman99/AeonProfiler#3]
Hello 
I really like the AeonProfiler.. it does a good job.. especially auto save on terminate, it saves when my program crashes.. The problem is I want to see all the calls in order.. until the crash happened not really profiling anyway I can convert this tool to do this? to list all function calls in order. Know of any tools for this purpose?.

I replaced SORT_UNUSED with SORT_INCREASING to `#` thinking the last call will be on the very end, but I couldn't find it feasible. 

```	{ TEXT("#"), SORT_Increasing, false, 50, false },							// column 1 (the row number)```

Modified the void `WINAPI ProcessCallTreeDataThread(LPVOID lpData)` removed `qsort` and all the `FindCallTreeRecord_BinarySearch` stuff.

![sdfsd](https://i.imgur.com/qMkxQud.png)

**Comment by botman99** [comment]
If you want a callstack at the time of the crash, you would probably just run your application in the Visual Studio debugger and it should break at an assert or exception.

**Comment by fatrolls** [comment]
The thing is it's not a program it's a plugin I cannot attach any debugger to it either it's protected process with a driver.

**Comment by botman99** [comment]
I don't know of a way to do what you want.

**Comment by fatrolls** [comment]
Your tool AeonProfiler works wonderfully just sorts the function calls which makes it not practical for tracing a crash function. `/Gh /GH ` works in my case.

When my program crashes it doesn't have any asserts or Exceptions it just silently exits.. but it still unloads all the DLL's which is good for AeonProfiler which saves on terminate aka the DLLMain unloading.

I think I found what I wanted it was made in 1998 I put it up on my github
https://github.com/fatrolls/CallMonitor

```
C:\Users\User\Desktop\callmonitor\Debug>Test 0 20
Test!main (002B2160)
        Test!threadFunc (002B20A0)
                Test!child1 (002B1F70)
                        Test!child2 (002B1FB0)
                        exit 002B1FB0, elapsed time=4 ms (13738100 ticks)
                        Test!child2 (002B1FB0)
                                Test!child1 (002B1F70)
                                        Test!child2 (002B1FB0)
                                        exit 002B1FB0, elapsed time=4 ms (12385575 ticks)
                                        Test!child2 (002B1FB0)
                                        exit 002B1FB0, elapsed time=5 ms (15019975 ticks)
                                exit 002B1F70, elapsed time=27 ms (82797408 ticks)
                        exception exit 002B1FB0, elapsed time=40 ms (122291193 ticks)
                exception exit 002B1F70, elapsed time=56 ms (170411060 ticks)
        exit 002B20A0, elapsed time=61 ms (184553835 ticks)
exit 002B2160, elapsed time=74 ms (222897953 ticks)

C:\Users\User\Desktop\callmonitor\Debug>
```
